name = "laporun"
pages_build_output_dir = "dist"

[vars]
# Pindahkan semua Env kamu di sini atau biarkan di Dashboard
# SUPABASE_URL = "isi_url_kamu"

[[kv_namespaces]]
binding = "SESSION"
id = "isi_id_kv_bebas_atau_buat_di_dashboard"